[versions]
android-compileSdk = "35"
android-targetSdk = "30"
android-minSdk = "23"
android-gradle = "8.8.0"
composeCompiler = "1.5.15"
dokka = "1.9.20"
kotlin = "1.9.25"
androidx-core = "1.7.0"
activity = "1.5.1"
groupie = "2.9.0"
appcompat = "1.6.1"
fragment = "1.4.1"
material = "1.6.1"
recyclerview = "1.2.1"
constraintlayout = "2.1.4"
androidx-test-junit = "1.1.5"
espresso = "3.5.1"
viewbinding-ktx = "1.2.3"
kotlinx-serialization = "1.4.1"
junit = "4.13.2"

[libraries]
androidx-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "composeCompiler" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version = "2025.05.01" }
androidx-compose-ui = { module = "androidx.compose.ui:ui" }
androidx-compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-compose-material = { module = "androidx.compose.material:material" }
androidx-compose-material-icons = { module = "androidx.compose.material:material-icons-core" }
androidx-core = { module = "androidx.core:core-ktx", version.ref = "androidx-core" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-activity-core = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity" }
androidx-fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
androidx-material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-test-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-test-junit" }
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
viewbinding-ktx = { module = "com.github.wada811:ViewBinding-ktx", version.ref = "viewbinding-ktx" }
groupie-core = { module = "com.github.lisawray.groupie:groupie", version.ref = "groupie" }
groupie-viewbinding = { module = "com.github.lisawray.groupie:groupie-viewbinding", version.ref = "groupie" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
android-application = { id = "com.android.application", version.ref = "android-gradle" }
android-library = { id = "com.android.library", version.ref = "android-gradle" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
